services:
  - type: web
    name: restrip-backend
    env: node
    region: oregon
    plan: free
    rootDir: server
    buildCommand: npm install --prefix server
    startCommand: npm start --prefix server
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: MONGO_URI
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: false
      - key: JWT_REFRESH_SECRET
        generateValue: false
      - key: JWT_ACCESS_EXPIRES
        value: "15m"
      - key: JWT_REFRESH_EXPIRES
        value: "7d"
      - key: CLIENT_URL
        sync: false
